rango/urls.py
from django.urls import path
from rango import views
from rango.views import AboutView, AddCategoryView, IndexView, AddPageView, ShowCategoryView, RestrictedView, RegisterProfileView, GoToView, ProfileView, ListProfileView


app_name = 'rango'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    #use of category_name_slug below must match parameter name in view definition
    path('category/<slug:category_name_slug>/', views.ShowCategoryView.as_view(), name='show_category'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.AddPageView.as_view(), name='add_page'),
    #path('register/', views.register, name='register'),
    #path('login/', views.user_login, name='login'),
    path('restricted/', views.RestrictedView.as_view(), name='restricted'),
    #path('logout/', views.user_logout, name='logout'),
    #path('search/', views.search, name='search'),
    path('goto/', views.GoToView.as_view(), name='goto'),
    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profiles/', views.ListProfileView.as_view(), name='list_profiles'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse
from rango.views import IndexView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('rango/', include('rango.urls')),  # maps any URL beginning rango/ to rango app
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Create your models here.
class Category(models.Model):
    max_length_char = 128
    name = models.CharField(max_length=max_length_char, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=Category.max_length_char)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # link UserProfile to User model instance
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Addition attributes to include
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.max_length_char, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # Meta is an inline class to provide addition info
    class Meta:
        # Associate ModelForm and a model (in this case, Category)
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Category.max_length_char, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page

        # decide fields to include in form
        # here we hide the foreign key (Category)
        exclude = ('category',)

        # we need either a fields or exclude line

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # if url not empty and doesn't begin with http:// we add it
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from rango.models import Category, Page, UserProfile
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from datetime import datetime
from rango.bing_search import run_query
from django.views import View
from django.utils.decorators import method_decorator

class IndexView(View):
    def get(self, request):
        # construct a dictionary to pass template engine as its context
        # boldmessage matches template variable in index.html
        # query database for all categories, order by number of likes
        # retrieve only top 5, place in context_dict
        category_list = Category.objects.order_by('-likes')[:5]
        page_list = Page.objects.order_by('-views')[:5]

        context_dict = {}
        context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
        context_dict['categories'] = category_list
        context_dict['pages'] = page_list

        # keep this call to increment the counter
        visitor_cookie_handler(request)

        # return rendered response to send to the client
        response = render(request, 'rango/index.html', context=context_dict)
        return response

class AboutView(View):
    def get(self, request):
        context_dict = {}

        visitor_cookie_handler(request)
        context_dict['visits'] = request.session['visits']

        return render(request, 'rango/about.html', context_dict)

class ShowCategoryView(View):

    def create_context_dict(self, category_name_slug):
        context_dict = {}

        try:
            # find category from slug?
            category = Category.objects.get(slug=category_name_slug)

            # retrieve all pages in this category (using filter())
            pages = Page.objects.filter(category=category)
            page_list = pages.order_by('-views')
            # Add results to context dict
            context_dict['pages'] = page_list

            # Also add category to verify (in the template) it exists
            context_dict['category'] = category
        except Category.DoesNotExist:
            context_dict['category'] = None
            context_dict['pages'] = None

        return context_dict

    def get(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        return render(request, 'rango/category.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        query = request.POST.get('query').strip()

        if query:
            context_dict['results_list'] = run_query(query)
            context_dict['query'] = query

        return render(request, 'rango/category.html', context_dict)

class AddCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = CategoryForm()
        return render(request, 'rango/add_category.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = CategoryForm(request.POST)

        # if the form valid?
        if form.is_valid():
            form.save(commit=True)
            # redirect back to index
            return redirect(reverse('rango:index'))
        else:
            # form contained errors
            # print them to the terminal
            print(form.errors)

        return render(request, 'rango/add_category.html', {'form': form})
'''
@login_required
def add_category(request):
    form = CategoryForm()

    # HTTP POST?
    if request.method == "POST":
        form = CategoryForm(request.POST)

        # if the form valid?
        if form.is_valid():
            form.save(commit=True)
            # redirect back to index
            return redirect('/rango/')
        else:
            # form contained errors
            # print them to the terminal
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})
'''

class AddPageView(View):
    def get_category_name(self, category_name_slug):
        try:
            category = Category.objects.get(slug=category_name_slug)
        except Category.DoesNotExist:
            category = None

        return category

    @method_decorator(login_required)
    def get(self, request, category_name_slug):
        form = PageForm()
        category = self.get_category_name(category_name_slug)

        if category is None:
            return redirect(reverse('rango:index'))

        context_dict = {'form': form, 'category': category}
        return render(request, 'rango/add_page.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        form = PageForm(request.POST)
        category = self.get_category_name(category_name_slug)

        if category is None:
            return redirect(reverse('rango:index'))

        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.views = 0
            page.save()

            return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)

        context_dict = {'form': form, 'category': category}
        return render(request, 'rango/add_page.html', context_dict)


'''
    --------------- Login/Registration code now handled by registration-redux
    
def register(request):
    registered = False

    if request.method == 'POST':
        # attempt to grab info from the raw form info
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        # if the two forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            # now hash the password, and update
            user.set_password(user.password)
            user.save()

            # now sort out the UserProfile instance
            # needed the User attribute first so commit = False for now
            profile = profile_form.save(commit=False)
            profile.user = user

            # did the user provide a picture
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            # profile registrationg was successful
            registered = True
        else:
            # something was wrong on the forms
            print(user_form.errors, profile_form.errors)
    else:
        # not an HTTP POST
        # render blank forms for user input
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html', context = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == 'POST':
        # gather username and password from form
        # use request.POST.get('') as it returns None if not found
        # rather than a KeyError if we used request.POST['']
        username = request.POST.get('username')
        password = request.POST.get('password')

        # built-in django machinery checks if this combination is valid
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            # login details do not match any User
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")

    else:
        # not a POST request
        return render(request, 'rango/login.html')

@login_required
def user_logout(request):
    # We know the user is logged in because of the decorator
    logout(request)
    return redirect(reverse('rango:index'))

    --------------- Login/Registration code now handled by registration-redux
'''

class RestrictedView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'rango/restricted.html')

def visitor_cookie_handler(request):
    # get number of visits to site
    # use the COOKIES.get() function
    visits = int(get_server_side_cookie(request, 'visits', '1'))    # default = 1 if nothing found

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    # if its been more than a day since last visit
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # update the last visit cookie
        request.session['last_visit'] = str(datetime.now())
    else:
        # set the last visit cookie
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

'''
def search(request):
    result_list = []
    query = ''
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
    return render(request, 'rango/search.html', {'result_list': result_list, 'query': query})
'''

class GoToView(View):
    def get(self, request):
        page_id = request.GET.get('page_id')
        try:
            page = Page.objects.get(id=page_id)
            page.views = page.views + 1
            page.save()
            return redirect(page.url)
        except Page.DoesNotExist:

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	About Rango
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Rango says...</h1>
			<div>
				<h2 class="h2">
				Here is the tutorial page.
				<strong>This tutorial has been put together by Duncan.</strong>
				</h2>
			</div>
		</div>
	</div>

	<div>
		<p>Visits: {{ visits}}</p>
	</div>

	<div>
		<a href="{% url 'rango:index' %}">Index</a><br />
		<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
		<img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
	</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add a Category
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Add a Category</h1>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.help_text }}
					{{ field }} <br />
					<div class="p-2"></div>
				{% endfor %}
				<br />
				<button class="btn btn-primary" type="submit" name="submit">Create Category</button>
				<div class="p-5"></div>
			</form>
		</div>
	</div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add a Page
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Add a Page to {{ category.name }}</h1>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.help_text }}
					{{ field }} <br />
					<div class="p-2"></div>
				{% endfor %}
				<br />
				<button class="btn btn-primary" type="submit" name="submit">Add Page </button>
				<div class="p-5"></div>
			</form>
		</div>
	</div>
{% endblock %}

templates/rango/base-old.html
<!DOCTYPE html>

{% load staticfiles %}
{% load rango_template_tags %}

<html>
	<head lang="en">
		<meta charset="UTF-8" />
		<title>Rango - 
			{% block title_block %}
				How to Tango with Django!
			{% endblock %}
		</title>
	</head>

	<body>
		<!-- page specific content -->
		<div>
			{% block body_block %}
			{% endblock %}
		</div>
		<div>
			{% block sidebar_block %}
				{% get_category_list %}
			{% endblock %}
		</div>
		<hr />
		<div>
			<ul>
				{% if user.is_authenticated %}
					<li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
					<li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
					<li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
					<li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
				{% else %}
					<li><a href="{% url 'registration_register' %}">Sign Up</a></li>
					<li><a href="{% url 'auth_login' %}">Login</a></li>
				{% endif %}
					<li><a href="{% url 'rango:about' %}">About</a></li>
					<li><a href="{% url 'rango:index' %}">Index</a></li>
			</ul>
		</div>
				
	</body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                    
                        {% if user.is_authenticated %}
                            <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                            <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}
                    {% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
	{% if categories %}
		{% for c in categories %}
			{% if c == current_category %}
				<li class="nav-item"><a class="nav-link active" href="{% url 'rango:show_category' c.slug %}"><span data-feather="archive"></span>{{ c.name }}</a></li>
			{% else %}
				<li class="nav-item"><a class="nav-link active" href="{% url 'rango:show_category' c.slug %}"><span data-feather="archive"></span>{{ c.name }}</a></li>
			{% endif %}
		{% endfor %}
	{% else %}
		<li class="nav-item"><strong>There are no categories present.</strong></li>
	{% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	{% if category %}
		{{ category.name }}
	{% else %}
		Unknown Category
	{% endif %}
{% endblock %}

{% block body_block %}
	{% if category %}
		<div class="jumbotron p-4">
			<div class="container">
				<h1 class="jumbotron-heading">{{ category.name }}</h1>
			</div>
		</div>
		{% if pages %}
			<ul>
				{% for page in pages %}
					<li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
					{% if page.views > 1 %}
		                ({{ page.views }} views)
		            {% elif page.views == 1 %}
		                ({{ page.views}} view)
		            {% endif %}
		        </li>
				{% endfor %}
			</ul>
		{% else %}
			<strong>No pages currently in category.</strong>
		{% endif %}

		{% if user.is_authenticated %}

		<a href="{% url 'rango:add_page' category.slug %}">Add Page</a><br />
		
		<div class="jumbotron p-4">
			<div class="container">
				<h1 class="jumbotron-heading">Search with Rango</h1>
			</div>
		</div>
		<div>
			<form class="form-inline" id="user-form" method="post" action="{% url 'rango:show_category' category.slug %}">
				{% csrf_token %}

				<div class="form-group">
					<input class="form-control" type="text" size="50" name="query" id="query" value="{{ query }}"/>
				</div>

				<button class="btn btn-primary" type="submit" name="submit">Search</button>
			</form>
		</div>
		<div>
			{% if result_list %}
				<h2>Results</h2>

				<div class="list-group">
					{% for result in result_list %}
						<div class="list-group-item">
							<h3 class="list-group-item-heading">
								<a href="{{ result.link }}">
									{{ result.title|safe|escape }}
								</a>
							</h3>
							<p class="list-group-item-text">
								{{ result.summary|safe|escape }}
							</p>
						</div>
					{% endfor %}
				</div>
			{% endif %}
		</div>

		{% endif %}

	{% else %}
		The specified category does not exist.
	{% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Homepage
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Rango says...</h1>
			<div>
				<h2 class="h2">
				{% if user.is_authenticated %}
					howdy {{user.username }}!
				{% else %}
					hey there partner!
				{% endif %}
				</h2>
				<strong>{{ boldmessage }}</strong><br />
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="card mb-6">
					<div class="card-body">
						<h2>Most Liked Categories</h2>
						<p class="card-text">
							{% if categories %}
								<ul class="list-group">
									{% for category in categories %}
										<li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
									{% endfor %}
								</ul>
							{% else %}
								<strong>There are no categories present.</strong>
							{% endif %}
						</p>
					</div>
				</div>
			</div>
			
			<div class="col-md-6">
				<div class="card mb-6">
					<div class="card-body">
						<h2>Most Viewed Pages</h2>
						<p class="card-text">
							{% if pages %}
								<ul class="list-group">
									{% for page in pages %}
										<li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a></li>
									{% endfor %}
								</ul>
							{% else %}
								<strong>There are no pages present.</strong>
							{% endif %}
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div>
		<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
	</div>



{% endblock %}

templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	User Profiles
{% endblock %}

{% block body_block %}
	
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">User Profiles</h1>
		</div>
	</div>

	<div class="container">
		<div class="row">
			{% if user_profile_list %}
			<div class="panel-body">
				<div class="list-group">
					{% for list_user in user_profile_list %}
						<div class="list-group-item">
							<h4 class="list-group-item-heading">
								<a href="{% url 'rango:profile' list_user.user.username %}">{{ list_user.user.username }}
								</a>
								{% if list_user.picture %}
									<img src="{{ MEDIA_URL }}{{ list_user.picture }}" width="30" height="30" alt="{{ list_user.username }}'s profile image" />
								{% else %}
									<img src="http://lorempixel.com/30/30" width="30" height="30" alt="No profile image" />
								{% endif %}
							</h4>
						</div>
					{% endfor %}
				</div>
			</div>
			{% else %}
				<p>There are no users present on Rango.</p>
			{% endif %}
		</div>
	</div>

{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Login
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Login to Rango</h1>
		</div>
	</div>
	<form id="login_form" method="POST" action="{% url 'rango:login' %}">
		{% csrf_token %}
		Username: <input type="text" name="username" value="" size="50" />
		<br />
		Password: <input type="password" name="password" value="" size="50" />
		<br />
		<input type="submit" value="submit" />
	</form>
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Restricted Page
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Since you are logged in, you can see this text!</h1>
		</div>
	</div>
{% endblock %}